spring:
  application:
    name: identity-service

  datasource:
    url: ${IDENTITY_DB_URL}
    username: ${IDENTITY_DB_USERNAME}
    password: ${IDENTITY_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

security:
  jwt:
    secret: ${JWT_SECRET_KEY}
    expiration: ${JWT_EXPIRATION}

server:
  port: ${IDENTITY_SERVICE_PORT}

