services:
  postgres:
    image: postgres:16
    container_name: qp-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_IDENTITY}
    ports:
      - "5432:5432"
    volumes:
      - qp_pg_data:/var/lib/postgresql/data


  rabbitmq:
    image: rabbitmq:3-management
    container_name: qp-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  qp_pg_data:
